### ISSUE TITLE
Add Featured Projects section somewhere [Separate Page or in the homepage itself]

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#12]

**Comment by ankan17** [comment]
Added featured projects section in homepage itself

**Comment by ghoshbishakh** [comment]
? and how did you close this without any PR? or comment hash?

**Comment by ghoshbishakh** [comment]
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by ankan17** [comment]
Okay.. What should I do? Ammend the commit with proper message?

**Comment by ghoshbishakh** [comment]
@ankan17 no need for that.
You should try to close issues through commits and PRs. with proper commit messages. See above link.
If you fail to do so then comment "Closing through <commit hash>"

**Comment by ankan17** [comment]
Closing through 39684a591b6fca473c0f477029853904708c591b
