### ISSUE TITLE
Add a page for linit and upload all PDFs

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#15]
https://drive.google.com/file/d/0B7D2iONEImRcTXZQeE5PUnpGSzQ/view?usp=sharing

https://drive.google.com/file/d/0B-hTKMU86vD6bjNVZEVzeGlqVFk/view?usp=sharing

**Comment by ankan17** [comment]
Should I add a separate page or add the file links in the existing section for LINIT?

**Comment by ghoshbishakh** [comment]
Separate page

**Comment by ghoshbishakh** [comment]
@ankan17 finish this one today

**Comment by ghoshbishakh** [comment]
@Compro-Prasad @ankan17 Please resolve this asap

**Comment by ghoshbishakh** [comment]
@ankan17 status

**Comment by ghoshbishakh** [comment]
@ankan17 can you work on this

**Comment by ankan17** [comment]
@ghoshbishakh Will resolve this issue by tonight.

**Comment by ankan17** [comment]
Temporary solution: 0a9fd315c2a64ce94b83af5a999b639cb8020b05. Will make a better styled page later. Can this issue be closed now?

**Comment by ghoshbishakh** [comment]
No please style. we can close it later

**Comment by ghoshbishakh** [comment]
Just add two thumbnails. And style them using bootstrap classes.
