### ISSUE TITLE
Navbar breaks between width of 615px and 793px(inclusive)

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/lugnitdgp.github.io#22]
![screenshot from 2017-08-29 21-09-59](https://user-images.githubusercontent.com/11143962/29833723-ffa9c930-8d09-11e7-8fe3-ec01f0921c51.png)

**Comment by ankan17** [comment]
Check with the new navbar

**Comment by Compro-Prasad** [comment]
No, there is a problem with the navbar. Try resizing the width of the window.

**Comment by ghoshbishakh** [comment]
@ankan17 that is not an issue actually. Normal screen sizes will be working well. Still check with popular device widths.
