### ISSUE TITLE
JavaScript errors of disqus on different posts

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/lugnitdgp.github.io#23]
![screenshot from 2017-08-30 12-29-43](https://user-images.githubusercontent.com/11143962/29859287-032c4d9c-8d7f-11e7-88c4-5780a4d2bfbb.png)

**Comment by ankan17** [comment]
When does this error occur?

**Comment by ghoshbishakh** [comment]
@Compro-Prasad steps to reproduce please

**Comment by Compro-Prasad** [comment]
1. Open Chromium in incognito window
2. Enter the address `https://lugnitdgp.github.io/blog`
3. Open the Inspector now
4. Switch to the `console` tab and keep it aside
5. Click on any of the posts
6. Wait for some time to let the error appear
7. If it doesn't then scroll the page to the disqus comments section

**Comment by ghoshbishakh** [comment]
Could not reproduce. Check @ankan17

**Comment by ankan17** [comment]
I did not get this error in Google Chrome

**Comment by Compro-Prasad** [comment]
That is the point. I too don't get this on Google Chrome but on Chromium. And on Firefox I get more errors and warnings.

**Comment by ankan17** [comment]
Let's keep this issue on hold for now because disqus is not fully configured yet. We need to provide the domain and identifier for disqus to work properly. First let me provide a value for those variables and then we'll see.

**Comment by Compro-Prasad** [comment]
It it is a problem with disqus, then disqus should handle it.
