### ISSUE TITLE
No navbar text on small devices

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#25]
![screenshot from 2017-08-31 10-01-11](https://user-images.githubusercontent.com/5156787/29906558-67d382ce-8e33-11e7-838f-6c69a2f287da.png)

Introduced in: https://github.com/lugnitdgp/lugnitdgp.github.io/commit/62c1718283a1969a79426e12b38da72b4a8d06ea

**Comment by ankan17** [comment]
Yes many websites keep only the brand logo on small devices removing the brand text.. What is the problem with that?

**Comment by ghoshbishakh** [comment]
Ok. accepted!
