### ISSUE TITLE
Blog page title

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#26]
![screenshot from 2017-08-31 10-04-40](https://user-images.githubusercontent.com/5156787/29906649-e44a3d3e-8e33-11e7-921c-203915066cab.png)

Is the title necessary?

**Comment by Compro-Prasad** [comment]
It doesn't matter to me whether its there or not.

**Comment by ankan17** [comment]
Maybe we can provide a better title in h1?

**Comment by ghoshbishakh** [comment]
Yes put a simple one.

**Comment by ghoshbishakh** [comment]
"Recent blog posts" should be enough
