### ISSUE TITLE
Horizontal scrolling enabled on mobile page of blog post. 

### ISSUE THREAD

**Issue by devanshgoenka97** [lugnitdgp/lugnitdgp.github.io#27]
Using Chrome for Android, it is seen that the blog post page has horizontal scroll enabled. 
![screenshot_2017-08-31-10-06-49-459_com android     ####chrome](https://user-images.githubusercontent.com/13414725/29906739-8cb52dee-8e34-11e7-8eda-1ef0ab458cd2.png)

**Comment by Compro-Prasad** [comment]
Did you try double clicking on the screen to zoom out?

**Comment by devanshgoenka97** [comment]
Double clicking results in this. 
![screenshot_2017-08-31-13-21-58-484_com android chrome](https://user-images.githubusercontent.com/13414725/29912521-90be66ce-8e4f-11e7-9f13-7ce94a4fd174.png)
There should be no margin outside the Nav.

**Comment by Compro-Prasad** [comment]
Thanks for the bug report. It will be fixed soon.
