### ISSUE TITLE
Number of comments is not being updated in blog

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#28]
![screenshot from 2017-08-31 11-45-04](https://user-images.githubusercontent.com/5156787/29909082-e5d49a56-8e41-11e7-85c4-2ec0d3a22654.png)

**Comment by ankan17** [comment]
I'll solve this issue once disqus is configured properly with domain name and page identifier

**Comment by ghoshbishakh** [comment]
So lets keep it open till that time

**Comment by ankan17** [comment]
I havr solved it.. It'll work fine now.. url was not configured properly, that's why the was issue was there.. you can close this now @ghoshbishakh
