### ISSUE TITLE
Add image for OnlineJ

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#32]

**Comment by ankan17** [comment]
Someone needs to provide an image for that

**Comment by ghoshbishakh** [comment]
@divyanshumehta screenshot please

**Comment by divyanshumehta** [comment]
Are we loking for a fav-icon or a logo?

**Comment by ghoshbishakh** [comment]
a screenshot or anything.. see lugnitdgp.github.io

**Comment by ghoshbishakh** [comment]
@divyanshumehta
