### ISSUE TITLE
Update How to join us page (send PR do not merge)

### ISSUE THREAD

**Issue by ghoshbishakh** [lugnitdgp/lugnitdgp.github.io#34]
Points to include in that:

1. Annual induction process
2. We will be happy to take people with GSoC or major Open Source contributions.
3. People can volunteer in our activities or contribute to our projects and gradually they will be absorbed into the club.
4. Students of other college may become a part of the club as our representative there.

@vartika-arora can you put these in a bit formal way and post it here.

**Comment by ghoshbishakh** [comment]
Also we need to add this link in the Navbar

**Comment by vartika-arora** [comment]
How to join us?
We at GNU/Linux User’s Group are always open to tech enthusiasts like ourselves! You can become a part of us in the following ways:
1. You are welcome to try for the auditions of the club which are conducted once a year.
2. A spot in the club is waiting for anyone who is a GSoCer or a major open-source contributor.
3. The volunteers in our activities and ventures and the avid contributors to our projects will gradually be absorbed into the club.
4. The students from other colleges can become a part of us as a representative of our club in their college.

**Comment by ankan17** [comment]
Check 265c794cc09582535bd69757d3d0282fab0b9810

**Comment by ghoshbishakh** [comment]
Thanks @ankan17 @vartika-arora 
Closing through 265c794
