### ISSUE TITLE
Styling Issue: Gap should be increased between two sections

### ISSUE THREAD

**Issue by Compro-Prasad** [lugnitdgp/lugnitdgp.github.io#35]
![screenshot from 2017-09-17 22-24-54](https://user-images.githubusercontent.com/11143962/30523162-ffeb20e4-9bcb-11e7-8b9a-39ef77dc14a6.png)

**Comment by ankan17** [comment]
Closing through a96c9f67b8419e2e2ba41a165e6149233708436c
